Traceback (most recent call last):
  File "/Users/ctf/Downloads/awesome/./sinkhole_server.py", line 57, in <module>
    main()
  File "/Users/ctf/Downloads/awesome/./sinkhole_server.py", line 48, in main
    httpd = HTTPServer(server_address, SinkholeHandler)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
